### ISSUE TITLE
cannot load such file -- rdoc (LoadError)

### ISSUE THREAD

**Issue by amadureira** [3ofcoins/chef-browser#67]
I installed on Centos 7. After install ruby rpm package and gems, I received this error: 

```
/usr/local/share/gems/gems/github-markup-1.4.0/lib/github/markup/rdoc.rb:2:in `require': cannot load such file -- rdoc (LoadError)
	from /usr/local/share/gems/gems/github-markup-1.4.0/lib/github/markup/rdoc.rb:2:in `<top (required)>'
	from /usr/local/share/gems/gems/github-markup-1.4.0/lib/github/markups.rb:2:in `require'
	from /usr/local/share/gems/gems/github-markup-1.4.0/lib/github/markups.rb:2:in `<module:Markup>'
	from /usr/local/share/gems/gems/github-markup-1.4.0/lib/github/markup.rb:53:in `instance_eval'
	from /usr/local/share/gems/gems/github-markup-1.4.0/lib/github/markup.rb:53:in `<module:Markup>'
	from /usr/local/share/gems/gems/github-markup-1.4.0/lib/github/markup.rb:5:in `<module:GitHub>'
	from /usr/local/share/gems/gems/github-markup-1.4.0/lib/github/markup.rb:4:in `<top (required)>'
	from /home/anderson.madureira/chef-browser/lib/chef-browser/app.rb:5:in `require'
	from /home/anderson.madureira/chef-browser/lib/chef-browser/app.rb:5:in `<top (required)>'
	from /home/anderson.madureira/chef-browser/lib/chef-browser.rb:1:in `require'
	from /home/anderson.madureira/chef-browser/lib/chef-browser.rb:1:in `<top (required)>'
	from /home/anderson.madureira/chef-browser/config.ru:7:in `require'
	from /home/anderson.madureira/chef-browser/config.ru:7:in `block in <main>'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /home/anderson.madureira/chef-browser/config.ru:in `new'
	from /home/anderson.madureira/chef-browser/config.ru:in `<main>'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
	from /usr/local/share/gems/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	from /usr/local/share/gems/gems/rack-1.6.0/bin/rackup:4:in `<main>'
```
I installed this RPMS
```
rpm -qa |egrep ruby
rubygem-psych-2.0.0-30.el7.x86_64
rubygem-rdoc-4.0.0-30.el7.noarch
rubygem-net-http-persistent-2.8-5.el7.noarch
rubygem-io-console-0.4.2-30.el7.x86_64
rubygem-bigdecimal-1.2.0-30.el7.x86_64
rubygem-thor-0.19.1-1.el7.noarch
rubygem-json-1.7.7-30.el7.x86_64
ruby-2.0.0.648-30.el7.x86_64
ruby-devel-2.0.0.648-30.el7.x86_64
ruby-irb-2.0.0.648-30.el7.noarch
rubygem-bundler-1.7.8-3.el7.noarch
ruby-libs-2.0.0.648-30.el7.x86_64
rubygems-2.0.14.1-30.el7.noarch
```

And this gems

```
addressable (2.3.8)
bigdecimal (1.2.0)
buff-config (1.0.1)
buff-extensions (1.0.0)
buff-ignore (1.1.1)
buff-ruby_engine (0.1.0)
buff-shell_out (0.2.0)
builder (3.2.2)
bundler (1.7.8)
capybara (2.5.0)
celluloid (0.16.0)
celluloid-io (0.16.2)
charlock_holmes (0.7.3)
chef-zero (4.3.2)
coderay (1.1.0)
cucumber (2.1.0)
cucumber-core (1.3.0)
deep_merge (1.0.1)
diff-lcs (1.2.5)
erubis (2.7.0)
escape_utils (1.0.1)
faraday (0.9.2)
ffi-yajl (2.2.2)
gherkin3 (3.1.2)
github-linguist (3.5.2)
github-markup (1.4.0)
hashie (3.4.2)
hitimes (1.2.3)
httpclient (2.6.0.1)
io-console (0.4.2)
json (1.8.3, 1.7.7)
kramdown (1.9.0)
libyajl2 (1.2.0)
method_source (0.8.2)
mime-types (1.25.1)
mini_portile (0.6.2)
mixlib-authentication (1.3.0)
mixlib-log (1.6.0)
multi_json (1.11.2)
multi_test (0.1.2)
multipart-post (2.0.0)
net-http-persistent (2.8)
nio4r (1.1.1)
nokogiri (1.6.6.2)
oj (2.12.14)
posix-spawn (0.3.11)
predicated (0.2.6)
pry (0.10.3)
psych (2.0.0)
puma (2.14.0)
pygments.rb (0.6.3)
rack (1.6.4, 1.6.0)
rack-protection (1.5.3)
rack-test (0.6.3)
rake (10.4.2)
rdoc (4.0.0)
retryable (2.0.2)
ridley (4.3.2)
ruby2ruby (2.2.0)
ruby_parser (3.7.1)
rugged (0.21.1b2)
semverse (1.2.1)
sexp_processor (4.6.0)
sinatra (1.4.6)
slop (3.6.0)
thor (0.19.1)
tilt (2.0.1)
timers (4.0.4)
tinyconfig (0.1.1)
uuidtools (2.1.5)
varia_model (0.4.1)
wrong (0.7.1)
xpath (2.0.0)
yajl-ruby (1.2.1)
```

All Gens were installed with bundle install

**Comment by amadureira** [comment]
Dears, 

To fix it, I put the module path on config. 

```
diff --git a/config.ru b/config.ru
index 4f85a9d..3160350 100644
--- a/config.ru
+++ b/config.ru
@@ -3,6 +3,7 @@ require 'bundler/setup'
 # Insert `lib/` subdirectory in front of require path
 _lib = File.join(File.dirname(__FILE__), 'lib')
 $:.unshift(_lib) unless $:.include?(_lib)
+$:.unshift('/usr/share/gems/gems/rdoc-4.0.0/lib')# unless $:.include?(_lib)
 
 require 'chef-browser'
```
I'm not sure if is a good practice, but it works for me.
