### ISSUE TITLE
NoMethodError at /cookbook/java-1.50.0

### ISSUE THREAD

**Issue by xamebax** [3ofcoins/chef-browser#70]
Trying to render a view of a newer cookbook (`/cookbook/java-1.50.0`) returns a NoMethodError. This happens with different Ruby versions, and with different cookbooks (I've experienced this with more than six). I'm using the real java cookbook. My first guess would be that it looks like the logic of handling metadata should be updated.

*Note*: I can still access filer or recipes of a cookbook if I enter the link in the browser directly, like so: `/cookbook/java-1.50.0?files`

### Stacktrace
![image](https://user-images.githubusercontent.com/967579/38733758-74dfcbe8-3f23-11e8-9ed1-9e311e2c50d0.png)

```
$ bundle exec rackup config.ru
Puma starting in single mode...
* Version 3.6.2 (ruby 2.3.0-p0), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9292
Use Ctrl-C to stop
127.0.0.1 - - [13/Apr/2018:13:53:56 +0200] "GET /cookbooks HTTP/1.1" 200 23407 0.4789
2018-04-13 13:54:00 - NoMethodError - undefined method `empty?' for nil:NilClass:
	/home/marta/other/chef-browser/views/cookbook.erb:17:in `block (2 levels) in singleton class'
	/home/marta/other/chef-browser/views/cookbook.erb:16:in `each'
	/home/marta/other/chef-browser/views/cookbook.erb:16:in `block in singleton class'
	/home/marta/other/chef-browser/views/cookbook.erb:-6:in `instance_eval'
	/home/marta/other/chef-browser/views/cookbook.erb:-6:in `singleton class'
	/home/marta/other/chef-browser/views/cookbook.erb:-8:in `__tilt_24043220'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:823:in `render'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:667:in `erb'
	/home/marta/other/chef-browser/lib/chef-browser/app.rb:222:in `block in <class:App>'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/nulllogger.rb:9:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:49:in `_call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:37:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/showexceptions.rb:24:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/chunked.rb:54:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:225:in `call'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/puma-3.6.2/lib/puma/server.rb:578:in `handle_request'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/puma-3.6.2/lib/puma/server.rb:415:in `process_client'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/puma-3.6.2/lib/puma/server.rb:275:in `block in run'
	/home/marta/.rvm/gems/ruby-2.3.0/gems/puma-3.6.2/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by xamebax** [comment]
Sorry I just opened a duplicate :embarrassed face:
